### ISSUE TITLE
Run vttestserver as MySQL 8.0

### ISSUE THREAD

**Issue by deepthi** [planetscale/vitess-framework-testing#121]
Depends on https://github.com/vitessio/vitess/issues/7470

Once that is fixed, the vitess+mysql 8.0 tests should run vttestserver with a version override so that we can catch anything specific to MySQL 8.0

**Comment by deepthi** [comment]
@mcronce this has been fixed in #118 and #119, is that correct?

**Comment by mcronce** [comment]
And vitessio/vitess#7474, yeah :)
