### ISSUE TITLE
Run all Rails tests in sharded mode

### ISSUE THREAD

**Issue by deepthi** [planetscale/vitess-framework-testing#125]
2 shards should be sufficient.
This will require specifying a vschema for all the tables being created.
VSchema can be created by executing DDLs as documented [here](https://github.com/vitessio/vitess/blob/master/examples/demo/vschema_ddls.sql).

**Comment by Akilan1999** [comment]
Me and manna had a discussion:
- We are planning to use a variable called $NUM_SHARDS as the Vitess docker image takes that as an argument 
- We will use vschema queries from the bash script (If we are running in shaded mode) .

**Comment by deepthi** [comment]
Sounds like a good plan :+1:

**Comment by GuptaManan100** [comment]
The addition of the first guide is at https://github.com/planetscale/vitess-framework-testing/pull/127
