### ISSUE TITLE
Get all current frameworks passing against MySQL 5.7 in CI

### ISSUE THREAD

**Issue by skottler** [planetscale/vitess-framework-testing#48]
Once https://github.com/planetscale/vitess-framework-testing/pull/47 there are six frameworks that need some attention to get running cleanly in CI:

- [x] javascript/typeorm
- [x] [php/laravel](https://github.com/planetscale/vitess-framework-testing/issues/48)
- [x] [mysqldump/import](https://github.com/planetscale/vitess-framework-testing/pull/49)
- [x] [python/sqlalchemy](https://github.com/planetscale/vitess-framework-testing/pull/59)
- [x] [ruby/rails](https://github.com/planetscale/vitess-framework-testing/pull/51)
- [x] [rust/sqlx](https://github.com/planetscale/vitess-framework-testing/pull/53)
- [x] [haskell/mysql-haskell](https://github.com/planetscale/vitess-framework-testing/pull/62)

This issue is intended to tracking getting those passing on `master`.

**Comment by mcronce** [comment]
BTW - just as a heads up before you dig into `sqlalchemy`, I'm working on that one :)
